name: Fetch Repo After Push
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python packages
        run: pip install -r requirements.txt
      - name: Configure SnowCLI
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          cd $GITHUB_WORKSPACE
          echo "[connections]" > connections.toml
          echo "[connections.default]" >> connections.toml
          echo "account = \"$SNOWFLAKE_ACCOUNT\"" >> connections.toml
          chmod 0600 connections.toml
      - name: Fetch Repo Using Creds in Env Variables
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_DEV_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          snow --config-file $GITHUB_WORKSPACE/connections.toml sql -q "ALTER GIT REPOSITORY PRUEBAS_ADRIAN.PUBLIC.streamlit_demo FETCH"